### ISSUE TITLE
Please address Mastodon feedback from Kristof

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/www-mastodon#111]
Did my best, if anything is confusing let's talk about it.

- [ ] "Get Server" button on the website needs to ask for a code – every solution has a code and you need to give a code to get access – in the UX it needs to point to how to get a code
- [ ] Add to TF Manual: how to obtain a code (needs to be decided)
- [ ] Need to confirm where the 30% goes to, should be a treasury wallet, needs to be created? (20% goes directly to the influencer / admin)
- [x] threefoldtech/www-mastodon#79
- [x] threefoldtech/www-mastodon#80
- [x] threefoldtech/www-mastodon#81
- [x] threefoldtech/test_feedback#346
- [x] threefoldtech/www-mastodon#82
- [x] threefoldtech/test_feedback#350
- [x] threefoldtech/www-mastodon#83

Please communicate what's doable now.

**Comment by xmonader** [comment]
I converted the things that I know, the first two items, I have no idea about.

**Comment by samtaggart** [comment]
The top three relate to the Solution Provider aspect.

Kristof wants it so that when you click on Get Server on mastodon.threefold.io, it asks for a code. Without a code, you can't launch a weblet. Because the code allows us to enable solution provider, which means we can send 20% to the host/admin and the other 30% goes to a foundation treasury. We want to enable this to give people incentives for launching their weblets. This you are aware of, correct? 

The second and third points are related to the first point, so we better level set on this first.

**Comment by samtaggart** [comment]
@xmonader Please check Telegram message from me for more info from Kristof.
